version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    image: dog-explorer-api:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/dog_explorer
      THE_DOG_API_KEY: ''
      JWT_SECRET: change-me-too
      JWT_REFRESH_SECRET: change-me-three
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
    # command: sh -c "npx ts-node-dev --esm --respawn --transpile-only --ignore-watch node_modules src/index.ts"

volumes:
  mongo_data:
    driver: local


